apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: todo-backend
        image: 100xdevs/todo-app-test:1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: port
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ecom-backend-secret
              key: db_url